dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {

}

scrolling {
    # 0.7 to 0.8 is the 'Golden Ratio' for scrolling
    # It gives you a large main window with a hint of the side ones
    column_width = 0.8 

    # IMPORTANT: If you only have ONE window, make it fill the whole screen
    fullscreen_on_one_column = true

    # Keeps the active window centered so you aren't looking at the edges
    focus_fit_method = 0

    direction = right


}

gestures {
}
