$background = rgb(02140C)
$foreground = rgb(c9e9e7)
$color0 = rgb(02140C)
$color1 = rgb(07768B)
$color2 = rgb(5C7A85)
$color3 = rgb(688E95)
$color4 = rgb(4AD1D7)
$color5 = rgb(9AA09F)
$color6 = rgb(C1C1AF)
$color7 = rgb(c9e9e7)
$color8 = rgb(8ca3a1)
$color9 = rgb(07768B)
$color10 = rgb(5C7A85)
$color11 = rgb(688E95)
$color12 = rgb(4AD1D7)
$color13 = rgb(9AA09F)
$color14 = rgb(C1C1AF)
$color15 = rgb(c9e9e7)
