$background = rgb(020105)
$foreground = rgb(f5c6f2)
$color0 = rgb(020105)
$color1 = rgb(4649C2)
$color2 = rgb(B22CB9)
$color3 = rgb(ED29DB)
$color4 = rgb(EE61EC)
$color5 = rgb(4A8FF4)
$color6 = rgb(9B94FC)
$color7 = rgb(f5c6f2)
$color8 = rgb(ab8aa9)
$color9 = rgb(4649C2)
$color10 = rgb(B22CB9)
$color11 = rgb(ED29DB)
$color12 = rgb(EE61EC)
$color13 = rgb(4A8FF4)
$color14 = rgb(9B94FC)
$color15 = rgb(f5c6f2)
