# ----------------------------
# Windows and workspaces
# ----------------------------

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = float, steam
windowrule = float, title:^(Volume Control)$
windowrule = size 800 600, title:^(Volume Control)$
windowrule = size 800 600, waypaper
windowrule = float, missioncenter
windowrule = size 1000 800, missioncenter
windowrule = float, waypaper
windowrule = float, pavucontrol
windowrule = plugin:hyprbars:nobar, steam
windowrule = plugin:hyprbars:nobar,^(firefox)$
windowrule = plugin:hyprbars:nobar,^(kitty)$


# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
